### ISSUE TITLE
Summarize what this module does and how to use it in README

### ISSUE THREAD

**Issue by dotsdl** [Becksteinlab/PDB_Ion_Survey#1]
The README file is the first stop for information on what a software package does. This should give a basic idea of what the purpose of the module is, as well as how to use it.

**Comment by orbeckst** [comment]
I hadn't even seen the issue when I wrote the blurb for the README.

@kaceyreidy should write the "How to use it." And you could also add a PDF of your report in a `doc/` subdirectory.
