### ISSUE TITLE
docs in notebook form

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/PDB_Ion_Survey#11]
Now that the package is installable  b58f38b  (excellent job @kaceyreidy !) we want to see how to use the package. As discussed, make a notebook for 
- [ ] Li+
- [ ] Na+

(and perhaps the other ions) to show how to do the full analysis from downloading files to making figures. I would add the notebooks under `docs/notebooks` where they will form the basis for your documentation. Importantly, the notebooks can also nicely viewed on GitHub or through http://nbviewer.jupyter.org.

**Comment by orbeckst** [comment]
Looking good.

Is there a way to mute the annoying
```
/usr/lib/python2.7/json/encoder.py:207: DeprecationWarning: Interpreting naive datetime as local 2017-02-22 14:32:21.385690. Please add timezone info to timestamps.
  chunks = self.iterencode(o, _one_shot=True)
```
warnings? (I am not even sure where they come from – matplotlib? – but I cannot reproduce in ipython). https://docs.python.org/2/library/warnings.html should have information.

**Comment by kaceyreidy** [comment]
I don't know; it just kinda happens.
