### ISSUE TITLE
restructure as a package

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/PDB_Ion_Survey#2]
Conceptually, the code to download pdbs and the code to pull the coordination from a structure are very different. The code will be easier to read if you put them into separate files ("modules"). You could then start making a complete python "package". Come up with a good, short name for the whole thing, let's say "pdbsurvey" and then make a directory of the same name and put the modules under it:
```
   README.md
   LICENSE
   pdbsurvey/
                    __init__.py              # empty file (just have a single comment in there, needed for python)
                    collection.py            # contains code to get PDB files
                    ioncoordination.py       # contains g(r) code
  doc/
                    report.pdf
  notebooks/
                    Radial_Distribution.ipynb
```

You can then import the modules as
```python
import pdbsurvey.collection
import pdbsurvey.ioncoordination
```

You can then also easily add other functionality such as 
* running analysis on many files
* other analysis tasks (e.g. finding out how deep ions are inside proteins)
without ending up with huge files of code that are impossible to read.

**Comment by kaceyreidy** [comment]
Should I delete the .gitignore file?

**Comment by orbeckst** [comment]
No, leave it. It makes working with git more convenient. 

--
Oliver Beckstein
email: orbeckst@gmail.com


Am Dec 11, 2015 um 7:43 schrieb "Kathleen Clark (Kacey Reidy)" <notifications@github.com>:

**Comment by kaceyreidy** [comment]
Okay, thanks.
