### ISSUE TITLE
Oxygen Selections

### ISSUE THREAD

**Issue by kaceyreidy** [Becksteinlab/PDB_Ion_Survey#8]
name O, O\*, \*O\*, ...

**Comment by orbeckst** [comment]
Is this a question how to select oxygens in MDAnalysis?

I *think* it should always work with
```python
u.select_atoms("name O*")
```

Are there *any* examples of an oxygen being called something like `1O` or something else of the form `*O`?

**Comment by kaceyreidy** [comment]
It seems to work with O* but I was planning to check that all of the oxygens are being selected.

**Comment by orbeckst** [comment]
On 5 Feb, 2016, at 09:44, Kathleen Clark (Kacey Reidy) wrote:

> It seems to work with O* but I was planning to check that all of the oxygens are being selected.

According to https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/tutorials/pdbintro.html#note1 (which is not the original source but I didn't have to find the statement in the actual official PDB docs), atom names start with the element symbol, so `O*` should cover everything and there's no ambiguity with anything else.

Protons (hydrogens) have special naming conventions and can start with numbers --- not really important for this issue but http://www.bmrb.wisc.edu/referenc/nomenclature/ might be a useful starting point if we ever need to look at it again.

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com
