### ISSUE TITLE
slice ion-ligand interaction by PDB metadata

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/PDB_Ion_Survey#9]
We want to be able to generate data for subsets of the whole PDB. In particular, we want to be able to
* select by resolution of the X-ray structure
* distinguish with or without resolved water molecules

We need to extract the relevant metadata from the PDB files (or the PDB itself) and associate it with the dataframes. Then it becomes easy to group analysis by e.g. resolution.

**Comment by kaceyreidy** [comment]
Solved using mdsynthesis sims and categories.
